cat > scripts/project_ops/cartographer.py <<'PY'
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
from pathlib import Path

DEFAULT_EXCLUDES = {
    ".git", ".venv", "node_modules", ".next", "dist", "build",
    ".pytest_cache", ".mypy_cache", "__pycache__", ".DS_Store",
    ".codex",  # runtime only; do not map it by default
}

def is_excluded(rel: Path) -> bool:
    parts = rel.parts
    return any(p in DEFAULT_EXCLUDES for p in parts)

def iter_paths(repo_root: Path, max_depth: int) -> list[Path]:
    out: list[Path] = []
    for p in repo_root.rglob("*"):
        rel = p.relative_to(repo_root)
        if is_excluded(rel):
            continue
        if len(rel.parts) > max_depth:
            continue
        out.append(p)
    return sorted(out, key=lambda x: str(x.relative_to(repo_root)).lower())

def write_tree(repo_root: Path, max_depth: int) -> None:
    lines: list[str] = []
    for p in iter_paths(repo_root, max_depth=max_depth):
        rel = p.relative_to(repo_root)
        depth = len(rel.parts)
        indent = "  " * (depth - 1)
        name = rel.parts[-1] + ("/" if p.is_dir() else "")
        lines.append(f"{indent}{name}")
    (repo_root / "Tree.txt").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

def write_project_map(repo_root: Path) -> None:
    docs = repo_root / "docs"
    docs.mkdir(parents=True, exist_ok=True)

    def exists(path: str) -> bool:
        return (repo_root / path).exists()

    links = []
    links.append("- Tree: `../Tree.txt`")
    if exists("AGENTS.md"):
        links.append("- Governance: `../AGENTS.md`")
    if exists("ARCHITECTURE.md"):
        links.append("- Architecture: `../ARCHITECTURE.md`")
    if exists("DECISIONS.md"):
        links.append("- Decisions: `../DECISIONS.md`")
    if exists("ROADMAP.md"):
        links.append("- Roadmap: `../ROADMAP.md`")
    if exists("REPO_PROFILE.json"):
        links.append("- Repo profile: `../REPO_PROFILE.json`")
    if exists("docs/diagrams/system"):
        links.append("- System diagrams: `diagrams/system/`")

    content = "# Project Map\n\n"
    content += "Generated by `cartographer.py`.\n\n"
    content += "## Quick links\n"
    content += "\n".join(links) + "\n\n"
    content += "## Notes\n"
    content += "- This file is an index, not a spec.\n"
    content += "- Update intent and rules in governance docs, not here.\n"

    (docs / "PROJECT_MAP.md").write_text(content, encoding="utf-8")

def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Tree.txt and docs/PROJECT_MAP.md for a repo.")
    ap.add_argument("--repo", default=".", help="Repo root (default: current directory)")
    ap.add_argument("--max-depth", type=int, default=6, help="Max directory depth (default: 6)")
    ap.add_argument("--all", action="store_true", help="Generate both Tree.txt and PROJECT_MAP.md")
    ap.add_argument("--tree", action="store_true", help="Generate Tree.txt only")
    ap.add_argument("--map", action="store_true", help="Generate docs/PROJECT_MAP.md only")
    args = ap.parse_args()

    repo_root = Path(args.repo).resolve()
    if not repo_root.exists():
        raise SystemExit(f"Repo path does not exist: {repo_root}")

    if args.all or (not args.tree and not args.map):
        write_tree(repo_root, max_depth=args.max_depth)
        write_project_map(repo_root)
    else:
        if args.tree:
            write_tree(repo_root, max_depth=args.max_depth)
        if args.map:
            write_project_map(repo_root)

    print(f"[cartographer] repo={repo_root}")
    if args.all or args.tree or (not args.tree and not args.map):
        print(f"[cartographer] wrote {repo_root / 'Tree.txt'}")
    if args.all or args.map or (not args.tree and not args.map):
        print(f"[cartographer] wrote {repo_root / 'docs' / 'PROJECT_MAP.md'}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
PY
